#git submodule add https://github.com/lilydjwg/colorizer.git bundle/colorizer
git submodule add https://github.com/plasticboy/vim-markdown.git bundle/vim-markdown
git submodule add https://github.com/Lokaltog/vim-powerline.git bundle/vim-powerline
git submodule add https://github.com/vim-scripts/UltiSnips.git bundle/ultisnips
git submodule add https://github.com/vim-scripts/auto_mkdir.git bundle/auto_mkdir
#git submodule add https://github.com/hlissner/vim-multiedit.git bundle/vim-multiedit
git submodule add https://github.com/tpope/vim-surround.git bundle/vim-surround
git submodule add https://github.com/tpope/vim-repeat.git bundle/vim-repeat
git submodule add https://github.com/git-mirror/vim-l9.git bundle/vim-l9
git submodule add https://github.com/scturtle/vim-instant-markdown-py.git bundle/vim-instant-markdown
#git submodule add https://github.com/davidhalter/jedi-vim bundle/jedi-vim
git submodule add https://github.com/vim-scripts/Conque-Shell.git bundle/conque-shell
#git submodule add https://github.com/majutsushi/tagbar.git bundle/tagbar
git submodule add https://github.com/tsaleh/vim-align.git bundle/vim-align
git submodule add https://github.com/kchmck/vim-coffee-script.git bundle/vim-coffee-script
#git submodule add https://github.com/vim-scripts/matrix.vim--Yang.git bundle/matrix
#git submodule add https://github.com/vim-scripts/FuzzyFinder.git bundle/fuzzyfinder
git submodule add https://github.com/kevinw/pyflakes-vim bundle/vim-pyflakes
git submodule add https://github.com/nathanaelkane/vim-indent-guides.git bundle/vim-indent-guides
git submodule add https://github.com/vim-scripts/OmniCppComplete.git bundle/omnicppcomplete
git submodule add https://github.com/vim-scripts/doxygen-support.vim.git bundle/doxygen-support
git submodule add https://github.com/mattn/zencoding-vim.git bundle/vim-zencoding
git submodule add https://github.com/scrooloose/nerdcommenter.git bundle/nerdcommenter
